### ISSUE TITLE
Review du fichier SecurityController.php

### ISSUE THREAD

**Issue by nicolas-scolari** [virginie-p/epic-friends-v2#2]
Si j'étais toi, j’enlèverais la fonction `dashboard` de ce Controller, je ne suis pas certain que ce soit sa place.

Je créerais un DashboardController avec la méthode en question.

```php
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    /**
     * @Route("/dashboard",  name="dashboard")
     */
    public function index()
    {
        $user = $this->getUser();
        $new_users = $this->getDoctrine()->getRepository(User::class)->findNewUsers($user); /* [Optim] - Tu peux chaîner ici, c'est pas déconnant... */
   
        return $this->render('connected/dashboard.html.twig', [
            'user' => $user,
            'new_users' => $new_users
        ]);
    }
}
```

**Comment by virginie-p** [comment]
En fait je l'ai appelé 'dashboard' mais c'est plutôt une histoire de nommage dans le sens ou en fait il s'agit de la home connectée. Elle se render lorsque l'utilisateur parvient à se connecter avec son login et mdp

**Comment by nicolas-scolari** [comment]
Certes Virginie, c'est donc la Route que tu vas appeler sur le `onAuthenticationSuccess` de ton `LoginFormAuthenticator`.
Moi, je l'aurais juste sorti du Controller car elle intervient après le process de Securité.
A toi de voir.

**Comment by virginie-p** [comment]
Ah yes, je vois ce que tu veux dire. Je l'ai bougé dans mon UserController du coup ;)
