### ISSUE TITLE
Review des Entities.

### ISSUE THREAD

**Issue by nicolas-scolari** [virginie-p/epic-friends-v2#3]
1)
Quand tu fais ça: 
`* @ORM\Column(type="string", length=255)`

sache que ça revient au même que de faire:  
`* @ORM\Column(type="string")`

parce que par défaut c'est 255.

2)
J'ai du mal à comprendre ton mapping entre `User`, `Interest` & `UserInterest`.
a) Qui, à terme, va renseigner les Interest? Un Admin ou les Users?
Je pense que le User va avoir à choisir dans une liste d'Interest mise à sa dispo....
b) Du coup, pour moi, la relation entre `User` et `Interest` est une ManyToMany.

3) 
Tu choisies parfois de faire la validation dans l'Entité et parfois dans le Form.
Les 2 sont valables (bien que j'ai une préférence perso) mais c'est toujours mieux de la mettre tjrs au même endroit.

**Comment by virginie-p** [comment]
Alors pour le 1. : 
Ce n'est pas moi qui l'ait renseigné ! c'est symfony car j'ai créé mes entités via la CLI

2 :
ça sera une liste administrable en back-office car l'utilisateur ne pourra pas créer un centre d'intérêt de son côté

3: 
En fait je choisis de faire dans le form quand il s'agit : soit d'un champ non-mappé, soit d'un formulaire ayant un fonctionnement spécifique. Si le champ est rattaché à une entité et a un fonctionnement identiques sur tous les forms, je mets la validation au niveau de l'entité :)

**Comment by nicolas-scolari** [comment]
1) Lol, ok :) C'était pour info, ne m'engueule pas ;)
2) Donc ManyToMany entre User (et en théorie c'est même UserProfile) & Interest.
3) Ok, ça se tient. Toujours pour info: C'est mal de mapper un Form sur une Entité (même si la doc te dit de le faire) et avec plus de pratique tu verras que tu passeras par une classe PHP intermédiare (un DTO, Data Transfert Object) qui fera la glue entre ton Form et ton Entité.

**Comment by virginie-p** [comment]
J'ai hâte d'en arriver là alors :) pour l'instant j'essaie déjà de maîtriser les bases ! ^^
